export {authPage} from './auth'
export {ChatPage} from './chat'
export {Page404} from './404'
export {Page500} from './500'
export {PageProfile} from './profile'
export {PageChange} from './changepassword'
export {registrationPage} from './registration'
export {Pagelist} from './listpage'
export {PageChangeMain} from './change'

